language: node_js
before_script: [
    "npm install"
  ]
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
notifications:
  email: false
script: mocha --compilers js:babel-core/register ./test/**/*.spec.js
os: "linux"